### ISSUE TITLE
An error occurred while executing doInBackground() CopyTask from USB to device

### ISSUE THREAD

**Issue by aditeTestAndroid** [magnusja/libaums#185]
Hi,
 First of all thanks for this helpful library. I am trying to view file from connected USB via OTG with sample app. As it try to copy file from USB to device it gives following error. 
Please help with this.
Thanks in advance.

****### 2019-05-09 17:03:28.011 17778-17844/com.github.mjdev.usbfileman E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.github.mjdev.usbfileman, PID: 17778
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
     
     ****### Caused by: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)****
        at org.jnode.util.ByteBufferUtils$ByteArray.refreshByteBuffer(ByteBufferUtils.java:75)
        at org.jnode.fs.ntfs.NTFSFile.read(NTFSFile.java:112)
        at com.github.magnusja.libaums.javafs.wrapper.fs.UsbFileWrapper.read(UsbFileWrapper.java:171)
        at com.github.mjdev.libaums.fs.UsbFileInputStream.read(UsbFileInputStream.java:84)
        at com.github.mjdev.libaums.usbfileman.MainActivity$CopyTask.doInBackground(MainActivity.java:317)
        at com.github.mjdev.libaums.usbfileman.MainActivity$CopyTask.doInBackground(MainActivity.java:285)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)****

**Comment by magnusja** [comment]
https://github.com/apache/felix/pull/114

Seems to be some problem with your Java setup and target Java version of your Android device
