### ISSUE TITLE
ConcurrentModification

### ISSUE THREAD

**Issue by gxshao** [magnusja/libaums#195]
### Problem
ConcurrentModification Exception throws

### Expected behavior
parallel create new file and hashmap throws exception down below

#### Stacktrace of Excpetion

```java
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.github.mjdev.libaums.fs.fat32.ShortNameGenerator.containShortName(ShortNameGenerator.java:209)
        at com.github.mjdev.libaums.fs.fat32.ShortNameGenerator.generateShortName(ShortNameGenerator.java:187)
        at com.github.mjdev.libaums.fs.fat32.FatDirectory.createFile(FatDirectory.java:350)
        at com.github.mjdev.libaums.fs.fat32.FatDirectory.createFile(FatDirectory.java:42)
```

**Comment by happyAshley** [comment]
may i know how you solve this problem? i I had the same problem

**Comment by happyAshley** [comment]
@gxshao may i know how you solve this problem? i I had the same problem
