### ISSUE TITLE
libaums crashed when pull out the usb device

### ISSUE THREAD

**Issue by lzxshare** [magnusja/libaums#305]
on some phones type checks usb device ,sometimes init device takes long time but had no response. when you pull out usb device,the application was crashed

here is erro log
Stack trace:  
```java.lang.RuntimeException: Error receiving broadcast Intent { act=android.hardware.usb.action.USB_DEVICE_DETACHED flg=0x1000010 (has extras) } in VebUsbReceiver@879c0f1
 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1727)
 at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
 at android.os.Handler.handleCallback(Handler.java:900)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:219)
 at android.app.ActivityThread.main(ActivityThread.java:8393)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

Caused by: kotlin.UninitializedPropertyAccessException: lateinit property usbCommunication has not been initialized
 at c.i.b.a.c.b(UsbMassStorageDevice.kt:1)
 at file.activity.BackupActivity.onDeviceDisConnected(BackupActivity.java:1)
 at VebUsbReceiver.onReceive(VebUsbReceiver.java:14)
 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1717)
```

it looks like usbCommunication has not been initialized，usbCommunication  is a private variable in the lib. so, how do i close the UsbMassStorageDevice safely？

**Comment by magnusja** [comment]
Fixed
