### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)

### ISSUE THREAD

**Issue by daiyongqiang1989** [magnusja/libaums#347]
Hi there
I using the lastest version 0.9.1，I find some other issues faced the same question。But I do not use Java 9+，thanks your relay。

**Comment by daiyongqiang1989** [comment]
Caused by: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at org.jnode.util.ByteBufferUtils$ByteArray.refreshByteBuffer(ByteBufferUtils.java:75)
        at org.jnode.fs.ntfs.NTFSFile.read(NTFSFile.java:112)

**Comment by daiyongqiang1989** [comment]
I use the java-fs souce code in my project.
