### ISSUE TITLE
New questions about libaums

### ISSUE THREAD

**Issue by makeking** [magnusja/libaums#358]
Today, I used the libaums library and found that there were multiple failures when exporting data, so I checked the logs for troubleshooting.
There are two situations:

First:
No JNI_OnLoad found in /data/app-lib/com.bete.turbidity-2/liberrno-lib.so 0x41f29f28, skipping init
java.io.IOException: Could not read from device, result == -1 errno 110 Connection timed out

Seconed : 
I/UsbMassStorageDevice: found usb device: UsbDevice[mName=/dev/bus/usb/001/007,mVendorId=1921,mProductId=21905,mClass=0,mSubclass=0,mProtocol=0,mInterfaces=[Landroid.os.Parcelable;@42639068]
I/UsbMassStorageDevice: found usb interface: UsbInterface[mId=0,mClass=8,mSubclass=6,mProtocol=80,mEndpoints=[Landroid.os.Parcelable;@426390f8]
    found usb endpoint: UsbEndpoint[mAddress=129,mAttributes=2,mMaxPacketSize=512,mInterval=0]
    found usb endpoint: UsbEndpoint[mAddress=2,mAttributes=2,mMaxPacketSize=512,mInterval=0]
D/UsbMassStorageDevice: setup device
I/UsbMassStorageDevice: MAX LUN 0
W/System.err: java.io.IOException: Could not write to device, result == -1 errno 110 Connection timed out
W/System.err:     at com.github.mjdev.libaums.usb.JellyBeanMr2Communication.bulkOutTransfer(JellyBeanMr2Communication.java:45)
        at com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.transferCommand(ScsiBlockDevice.java:143)
        at com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.init(ScsiBlockDevice.java:86)
        at com.github.mjdev.libaums.UsbMassStorageDevice.setupDevice(UsbMassStorageDevice.java:231)
        at com.github.mjdev.libaums.UsbMassStorageDevice.init(UsbMassStorageDevice.java:191)
        at com.bete.turbidity.ui.view.ExportDataView$1.onClick(ExportDataView.java:190)
        at android.view.View.performClick(View.java:4463)
W/System.err:     at android.view.View$PerformClick.run(View.java:18789)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5325)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
        at dalvik.system.NativeStart.main(Native Method)

So, I want to know the answers to these two questions, Thanks!

**Comment by magnusja** [comment]
The connection to the USB device times out. Try another OTG adapter.
